import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../../assets/css/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <main>
        <div className="text-3xl font-bold underline">home</div>
        <div className='bg-[white] p-10 rounded-xl mt-10'>nguyen dac cuong</div>
      </main>
    </div>
  );
};

export default Home;
