import { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import useTrans from 'src/hooks/useTrans';

const Home: NextPage = ({ posts }: any) => {
  const trans = useTrans();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div className='text-3xl font-bold underline'>{trans.home.title}</div>
        <div>{trans.home.content}</div>
        <div className='bg-[white] p-10 rounded-xl mt-10'>
          {!posts ? (
            <div>not found</div>
          ) : (
            posts.map((v: any, index: any) => <div key={index}>{v.name}</div>)
          )}
        </div>
      </main>
    </div>
  );
};

export default Home;
