import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../../assets/css/Home.module.css';
import vercel from '../../assets/svg/vercel.svg';
import Image from 'next/image';
import dynamic from 'next/dynamic';
import { Suspense } from 'react';

const DynamicHeader = dynamic(() => import('../components/elements/demo'), {
  suspense: true,
});

const Test: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Test</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <main className={styles.main}>
        <div>Test</div>
        <Image
          src={vercel}
          alt="Picture of the author"
        />
        <Suspense fallback={`Loading...`}>
          <DynamicHeader />
        </Suspense>
      </main>
    </div>
  );
};

export default Test;
